#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'athena-motor-control','console_scripts','motor_control'
__requires__ = 'athena-motor-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('athena-motor-control', 'console_scripts', 'motor_control')()
    )
