# Service definition for the GetState service used to get the current state of a single node.
---
bool success # Indicates the status of the request
string state # The string representation of the state
int64 int_state = -1 # Integer representation (Optional)