#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'athena-guidance-system','console_scripts','guidance_system'
__requires__ = 'athena-guidance-system'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('athena-guidance-system', 'console_scripts', 'guidance_system')()
    )
