#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'naiad-driver','console_scripts','motor_driver'
__requires__ = 'naiad-driver'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('naiad-driver', 'console_scripts', 'motor_driver')()
    )
