athena:
  motor_control:
    ros__parameters:
      motor_update_frequency: 100.0
  navigation:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params atm.
  mission_control:
    ros__parameters:
      placeholder: 0
  position:
    ros__parameters:
      placeholder: 0