naiad:
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
        z: 7
      scale_linear:
        x: 0.15
        z: -0.15
      scale_linear_turbo:
        x: 0.3
        z: -0.3

      axis_angular:
        yaw: 0
        pitch: 4
        roll: 3
      scale_angular:
        yaw: 0.15
        pitch: 0.15
        roll: 0.15
      scale_angular_turbo:
        yaw: 0.3
        pitch: 0.3
        roll: 0.3

      enable_button: 5  # R1 shoulder button
      enable_turbo_button: 2  # Triangle button