athena:
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
      scale_linear:
        x: 0.3
      scale_linear_turbo:
        x: 0.7

      axis_angular:
        yaw: 0
      scale_angular:
        yaw: 0.3
      scale_angular_turbo:
        yaw: 0.7

      enable_button: 5  # R1 shoulder button
      enable_turbo_button: 2  # Triangle button