athena:
  motor_control:
    ros__parameters:
      motor_update_frequency: 50.0     # Hz - The frequency at which the motor controller computes new motor output values and sends to the motor driver.
      pas_orientation_update_freq: 0.5 # Hz - The frequency at which the motor controller computer a new point and shoot orientation. 
                                       #      This doesn't need to happen that often.
      pas_threshold: 0.0   # The threshold that decided if PaS orientation should be used instead of the goal orientation. Distance in meters from the goal.  
      goal_distance_slack: 0.2 # Meters
      goal_orientation_slack: 0.1 # Percent.
  navigation:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params for this node atm.
  mission_control:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params for this node atm.
  position:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params for this node atm.
  motor_driver:
    ros__parameters:
      motor_output_silence_period: 100 # Allowed time period in milliseconds that the motor driver
                                       # will operate without receiving a command from motor contorl.