athena:
  motor_control:
    ros__parameters:
      motor_update_frequency: 100.0
  navigation:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params for this node atm.
  mission_control:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params for this node atm.
  position:
    ros__parameters:
      placeholder: 0 # Placeholder since there are no params for this node atm.