geometry_msgs/Pose pose       # Pose to hold
int64 duration  # Holding duration in seconds. 0=Infinite
---
int64 duration              # Duration position was held
int16 status                # Status of the action. 1 = moving to pose, 2 = holding, 3 = Finished.
string message              # Informational message about the status
geometry_msgs/Pose pose_mean     # The mean pose held over time 
geometry_msgs/Pose pose_variance # Variance of the poses held over time
---
int16 status                # Status of the action. 1 = moving to pose, 2 = holding, 3 = Finished.
string message              # Informational message about the status
geometry_msgs/Pose pose_mean     # The mean pose held over time 
geometry_msgs/Pose pose_variance # Variance of the poses held over time