#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'athena-mission-control','console_scripts','mission_control'
__requires__ = 'athena-mission-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('athena-mission-control', 'console_scripts', 'mission_control')()
    )
