# The current state estimate (sent as a simple flat array and made into a column at the sensor node)
float32[] state

# The covariance of the state estimate (sent flat and reconstructed using reshape, since it always has as many rows and columns as state has elements/rows)
float32[] covar

---
# The calculated residual (is flat and made into a column in position node, like the state)
float32[] residual

# The kalman gain (reconstructed at destination, like covar. Should be reshaped with as many rows as there are residual elements, and as many columns as there are state elements (as far as i know))
float32[] gain

# The observation matrix, calculated using the Jacobian (reconstructed like gain, but reversed, with x rows and y columns)
float32[] observationmatrix
